### ISSUE TITLE
Hash changes on every build for chunks that import style files 

### ISSUE THREAD

**Issue by HosseinAgha** [alexindigo/webpack-chunk-hash#11]
I found that if you `require or import` style files (using `style-loader` or extractTextPlugin) chunkHashes change even if I don't change any files within the chunk.  
I couldn't find any similar issues. I think css-modules messes with chunkhash.
I use `webpack 2.7.0` and the latest version of this plugin.

**Comment by CNDonny** [comment]
i have the fucking same problem

**Comment by HosseinAgha** [comment]
I'm going to close this. you can find more detailed issue here https://github.com/webpack-contrib/css-loader/issues/582
